### PR TITLE
Update composer.json to accept october 3.1

### PR DESCRIPTION
**Pull request by gldrenthe89**
Added october v3.1

### CODE REVIEW

**Comment by gldrenthe89** [comment]
Please accept this PR so people can actually install this in October v3.1 and up

**Comment by renickbuettner** [comment]
Sorry for the delay in response. Thank you for your support!

**Comment by gldrenthe89** [comment]
> Sorry for the delay in response. Thank you for your support!

No problem. thanks for merging

**Comment by gldrenthe89** [comment]
Are you also making a release tag ?

**Pull request merged**
